[package]
authors = ["Parity Technologies <admin@parity.io>"]
name = "cumulus-relay-chain-rpc-interface"
version = "0.1.0"
edition = "2021"


[dependencies]
polkadot-service = { git = "https://github.com/PureStake/polkadot", branch = "moonbeam-polkadot-v0.9.37" }

cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-relay-chain-interface = { path = "../relay-chain-interface" }

sp-api = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-core = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-consensus-babe = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-authority-discovery = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-state-machine = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-storage = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sc-client-api = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sc-rpc-api = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
tokio = { version = "1.24.1", features = ["sync"] }

futures = "0.3.25"
futures-timer = "3.0.2"
parity-scale-codec = "3.2.1"
jsonrpsee = { version = "0.16.2", features = ["ws-client"] }
tracing = "0.1.37"
async-trait = "0.1.60"
url = "2.3.1"
serde_json = "1.0.91"
serde = "1.0.152"
lru = "0.8.1"
