[package]
name = "cumulus-client-consensus-relay-chain"
description = "The relay-chain provided consensus algorithm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.60"
futures = "0.3.25"
parking_lot = "0.12.1"
tracing = "0.1.37"

# Substrate
sc-consensus = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-api = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-block-builder = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-blockchain = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-consensus = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-core = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-inherents = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
sp-runtime = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }
substrate-prometheus-endpoint = { git = "https://github.com/PureStake/substrate", branch = "moonbeam-polkadot-v0.9.37" }

# Cumulus
cumulus-client-consensus-common = { path = "../common" }
cumulus-primitives-core = { path = "../../../primitives/core" }
cumulus-relay-chain-interface = { path = "../../relay-chain-interface" }
