on:
  pull_request:
    branches:
      - mangata-dev
  push:
    branches: [ mangata-dev ]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install newset Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-05-11
          default: true
      - name: Install nightly-2022-05-11 with wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-05-11
          target: wasm32-unknown-unknown
      - name: Check Cargo version
        run: |
          cargo --version
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2022-05-11
          command: build
          args: --release -j2
      - name: Build UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2022-05-11
          command: test
          args: --release -j2 --no-run
      - name: Run UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2022-05-11
          command: test
          args: --release
